Controllers/AppController.cs
using HotelManagement.Data;
using HotelManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotelManagement.Controllers
{
    public class AppController : Controller
    {
        private readonly IHotelRepository _repository;

        public AppController(IHotelRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            var results = _repository.GetAllRooms().AsQueryable();
            return View(results);
        }

        public IActionResult EditRoom(int id)
        {
            return View(_repository.GetRoomById(id));
        }

        public IActionResult CreateRoom()
        {
            return View();
        }

        [Authorize]
       // [HttpGet("MainPage")]
        public IActionResult MainPage()
        {
            return View();
        }

        [HttpGet("RoomManagement")]
        public IActionResult RoomManagement()
        {
            var results = _repository.GetAllRooms().AsQueryable();
            return View(results);
        }
        [HttpPost("RoomManagement")]
        public IActionResult RoomManagement(RoomManagementViewModel model)
        {
            if(ModelState.IsValid)
            {
                //do smth
            }
           else
            {
                //smth else
            }
            return View();
        }

        [HttpGet("ReservationManagement")]
        public IActionResult ReservationManagement()
        {
            return View();
        }

        [Authorize]
        [HttpGet("Calendar")]
        public IActionResult Calendar()
        {
            return View();
        }
    }
}

Controllers/RoomsController.cs
using AutoMapper;
using HotelManagement.Data;
using HotelManagement.Data.Entities;
using HotelManagement.ViewModels;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotelManagement.Controllers
{
    [Route("api/[Controller]")]
    [ApiController]
    public class RoomsController : Controller
    {
        private readonly IHotelRepository _repository;
        private readonly IMapper _mapper;

        public RoomsController(IHotelRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public ActionResult<IEnumerable<Room>> Get()
        {
            try
            {
                return Ok(_repository.GetAllRooms());
            }
            catch (Exception)
            {
                return BadRequest("Nu s-au putut gasi camerele!");
            }
        }

        [Route("id")]
        public IActionResult Get(int id)
        {
            try
            {
                var room = _repository.GetRoomById(id);

                if (room != null) return Ok(_mapper.Map<Room, RoomManagementViewModel>(room));
                else return NotFound();
            }
            catch (Exception ex)
            {
                return BadRequest($"Failed to get room {id}");
            }
        }

        [Route("{id}")]
        public ActionResult Delete(int id)
        {
            try
            {
                _repository.DeleteRoomById(id);
                if (_repository.SaveAll())
                {
                    return RedirectToAction("RoomManagement", "App");
                }

            }
            catch (Exception)
            {
                return BadRequest($"Failed to delete room {id}");
            }
            return BadRequest($"Failed to delete room {id}");
        }

        //[HttpPost]
        //public IActionResult Post([FromBody] RoomManagementViewModel model)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            model.HotelId = _repository.GetHotel().Id;
        //            var newRoom = _mapper.Map<RoomManagementViewModel, Room>(model);

        //            _repository.AddEntity(newRoom);
        //            if (_repository.SaveAll())
        //            {
        //                return Created($"/api/rooms/{newRoom.Id}", _mapper.Map<Room, RoomManagementViewModel>(newRoom));
        //            }
        //        }
        //        else
        //        {
        //            return BadRequest(ModelState);
        //        }

        //    }
        //    catch (Exception ex)
        //    {
        //        return BadRequest("Camera nu a putut fi salvata.");
        //    }

        //    return BadRequest("Camera nu a putut fi salvata.");
        //}

        [HttpPost("id")]
        public IActionResult Add([FromForm] Room model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.HotelId = _repository.GetHotel().Id;

                    _repository.AddEntity(model);
                    if (_repository.SaveAll())
                    {
                        // return Created($"/api/rooms/{model.Id}", model);
                        return RedirectToAction("RoomManagement", "App");
                    }
                }
                else
                {
                    return BadRequest(ModelState);
                }

            }
            catch (Exception ex)
            {
                return BadRequest("Camera nu a putut fi salvata.");
            }

            return BadRequest("Camera nu a putut fi salvata.");
        }

        [HttpPost]
        public IActionResult Edit([FromForm]Room model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repository.ModifyRoomState(model);
                    return RedirectToAction("RoomManagement", "App");
                   
                }
                else
                {
                    return BadRequest(ModelState);
                }

            }
            catch (Exception ex)
            {
                return BadRequest("Modificarile nu au putut fi salvate.");
            }
        }
    }
}

Views/Shared/CreateRoom.cshtml
@using System
@using NonFactors.Mvc.Grid;
@model HotelManagement.Data.Entities.Room

<head>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">
</head>
@section Scripts{
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}
<div class="col-md-4 offset-md-4">
    <div class="card card-body bg-light">
        <form asp-controller="Rooms" asp-action="Add" method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="RoomNumber">Numarul Camerei:</label>
                <input type="number" asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonCapacity">Numar de persoane:</label>
                <input type="number" asp-for="PersonCapacity" class="form-control" />
                <span asp-validation-for="PersonCapacity" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsUsable">Este utilizabila?</label>
                <select asp-for="IsUsable" class="form-control" asp-items="Html.GetEnumSelectList<HotelManagement.Data.Enums.DaNu>()">
                    <option selected="selected" value="">Va rog selectati</option>
                </select>
                <span asp-validation-for="IsUsable" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Descriere:</label>
                <textarea rows="5" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adaugare" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>
@*<div class="modal" id="myModel" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4>cacaaaaa</h4>
                </div>

            </div>

        </div>
    </div>*@
<div>
    <p>show smth pls</p>
</div>

Views/Shared/EditRoom.cshtml
@using System
@using NonFactors.Mvc.Grid;
@model HotelManagement.Data.Entities.Room

<head>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">
</head>
@section Scripts{
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}
<div class="col-md-4 offset-md-4">
    <div class="card card-body bg-light">
        <form asp-controller="Rooms" asp-action="Edit" method="post">
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.HotelId)
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="RoomNumber">Numarul Camerei:</label>
                <input type="number" asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonCapacity">Numar de persoane:</label>
                <input type="number" asp-for="PersonCapacity" class="form-control" />
                <span asp-validation-for="PersonCapacity" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsUsable">Este utilizabila?</label>
                <select asp-for="IsUsable" class="form-control" asp-items="Html.GetEnumSelectList<HotelManagement.Data.Enums.DaNu>()">
                    <option selected="selected" value="">Va rog selectati</option>
                </select>
                <span asp-validation-for="IsUsable" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsOccupied">Este ocupata?</label>
                <select asp-for="IsOccupied" class="form-control" asp-items="Html.GetEnumSelectList<HotelManagement.Data.Enums.DaNu>()">
                    <option selected="selected" value="">Va rog selectati</option>
                </select>
                <span asp-validation-for="IsOccupied" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Descriere:</label>
                <textarea rows="5" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Editare" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>
@*<div class="modal" id="myModel" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4>cacaaaaa</h4>
                </div>

            </div>

        </div>
    </div>*@

Views/Shared/_Layout.cshtml
@*@{
    ViewBag.Title = "Home Page";

}*@
<!DOCTYPE html>
<html>
<head>
    <link href='~/node_modules/@@fullcalendar/core/main.css' rel='stylesheet' />
    <link href='~/node_modules/@@fullcalendar/timeline/main.css' rel='stylesheet' />
    <link href="~/node_modules/@@fullcalendar/resource-timeline/main.css" rel="stylesheet" />
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">
    <script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/tooltip.js/dist/umd/tooltip.min.js"></script>
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
            <h1 class="navbar-brand">Bun venit la Hotel Management!</h1>
            <div>
                <ul class="navbar-nav">
                    @*<li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Index">Login</a></li>*@
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="MainPage">Pagina principala</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="RoomManagement">Prelucrarea camerelor</a></li>
                    @*<li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="ReservationManagement">Reservation Management</a></li>*@
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Calendar">Calendar</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="navbar-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="navbar-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
        @* @Html.AjaxGrid(Url.Action("ReservationManagement"))*@
        <br />
    </section>
    <footer class="container">
        <div class="text-center">Copyright 2020 Denisa Inc</div>
    </footer>
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script>
        document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));
    </script>
    @RenderSection("scripts", false)
</body>
</html>